---
title: "Degree Days"
author: "Sara DeLaurentis"
date: "5/5/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(stringr)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(zoo)


```

## Data setup

```{r data setup}

## TEMPORARILY SET WORKING DIRECTORY TO "Itasca_project_19-21" !!!! ##

data <- read.csv("ALL.csv")

data$date.time <- data$date.time %>% as.POSIXlt(tz = "") #set date/time class to POSIXlt for greater ease in parsing date elements.
head(data$date.time)

# -- subset by date, add week-counting columns, calculate weekly means --

START <- as.POSIXlt("2020-10-01 00:00:00", tz = "") #trying the october 1-yr set to see if the code works. 5-5, SD
#BREAK <- as.POSIXlt("2020-08-25", tz = "")
#RESUME <- as.POSIXlt("2020-09-30", tz = "")
END <- as.POSIXlt("2021-10-01 00:00:00", tz = "")

data[is.na(data$value),] %>% #there should be a handful of NA's present if you're working with the right version of .csv files.
  print()

data <- data %>% 
  subset.data.frame(date.time >= START & date.time <= END) %>% #subset the whole df                         
  filter(!is.na(value))  # Apply filter & !is.na

# remove partial datasets for the given window. Anything with less than 500 values gets removed.
data <- data %>%
  group_by(site, rep, position) %>% 
  mutate(length = length(date.time)) %>% 
  filter(length > 500)


```

## 

```{r daily means}

daily.means.df <- data %>%
  group_by(site, rep, position, date(date.time)) %>% 
  summarise(date = date(date.time),
            name = name,
            site = site, 
            rep = rep, 
            position = position, 
            meantemp = round(mean(value), 2)) #BIG QUESTION: WHEN SHOULD I ROUND?
daily.means.df <- distinct(daily.means.df, site, rep, position, date, .keep_all = TRUE) %>% 
  ungroup()
daily.means.df$`date(date.time)` <- NULL

view(daily.means.df)

```


```{r degree days one}

daily.means.df <- daily.means.df %>% 
  filter(meantemp > 0) 
#only select days where mean temperature is greater than 0 

DD.df1 <- daily.means.df %>% 
  group_by(site, rep, position) %>% 
  summarise(site = site, #keep these columns: site, rep, position
            rep = rep,
            position = position, #create degree.days column by outputting the sum of meantemp for each position. (Not sensor, but position)
            degree.days = sum(meantemp)) %>% 
  distinct(site, rep, position, .keep_all = TRUE) %>% 
  ungroup()
view(DD.df1)  

DD.df2 <- daily.means.df %>% 
  mutate(year.mon = format(as.Date(date), "%Y-%m")) %>% 
  group_by(site, rep, position, year.mon) %>% 
  summarize(month.GDD = sum(meantemp)) %>% 
  ungroup()
view(DD.df2)

DD.df2 <- DD.df2 %>% 
  pivot_wider(names_from = year.mon, values_from = month.GDD) #puts year.mon into their own columns

degree.days.dfW <- left_join(DD.df1, DD.df2)

view(degree.days.dfW)

write_csv(degree.days.dfW, "degree_days_OCT_v2.csv") #write the csv file.

```

```{r plots}

#pivot to long? Not sure if needed


#Change to factors
cols <- c("site", "rep", "position")
degree.days.dfW[cols] <- lapply(degree.days.df[cols], factor)



myplot <- ggplot(data = degree.days.dfW, aes(x = position, y = degree.days, color = site)) +
      geom_point() +
 # facet_wrap(~position, ncol = 2)
      labs(title = "Growing Degree Days by Site",
           subtitle = "Date Range: October 1, 2020 - September 30, 2021",
           y = "GDD, accumulated mean temperature",
           x = "Site") + theme_bw(base_size = 15)
      print(myplot)

```

