---
title: "Trapezoidal_rule_2020_05_13"
author: "Sara DeLaurentis"
date: "5/13/2022"
output: html_document
---

```{r setup, include=FALSE}


library(stringr)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(zoo)

```

##
From:
https://www.r-bloggers.com/2017/08/the-trapezoidal-rule-of-numerical-integration-in-r/
Accessed: 2022-05-13, 14:25

```{r trap example one}

f <- function(x) {
  return(x * sin(x))
}
# Create a data frame to store all the points needed for the approximation trapezoid
df <- data.frame(cbind(c(0, pi/4, pi/4, 0), c(0, f(pi/4), 0, 0)))
# Plot the function and its approximation by the trapezoidal rule
ggplot(data = data.frame(x = 0), mapping = aes(x = x)) + 
  stat_function(fun = f, size = 1.05, alpha = 0.75, color='blue') + 
  geom_segment(aes(x = 0, y = 0, xend = pi/4, yend = f(pi/4))) + 
  geom_segment(aes(x = pi/4, y = 0, xend = pi/4, yend = f(pi/4))) + 
  geom_polygon(data = df, aes(x=X1, y=X2), fill = 'blue', alpha = 0.2) + 
  geom_area(stat = 'function', fun = f, fill = 'black', alpha = 0.3, xlim = c(0, pi/4)) + 
  xlim(c(-0.5,1))



```

## 

```{r trap example two}


f2 <- function(x) {
  return(x^2 * exp(-x))
}
df <- data.frame(cbind(c(0, 1, 1, 0), c(0, f2(1), 0, 0)))
ggplot(data = data.frame(x = 0), mapping = aes(x = x)) + 
  stat_function(fun = f2, size = 1.05, alpha = 0.75, color='blue') + 
  geom_segment(aes(x = 0, y = 0, xend = 1, yend = f2(1))) + 
  geom_segment(aes(x = 1, y = 0, xend = 1, yend = f2(1))) + 
  geom_polygon(data = df, aes(x=X1, y=X2), fill = 'blue', alpha = 0.2) + 
  geom_area(stat = 'function', fun = f2, fill = 'black', alpha = 0.3, xlim = c(0, 1)) + 
  xlim(c(0,1))


```
```{r trap example three}

trapezoid <- function(f, a, b) {
  if (is.function(f) == FALSE) {
    stop('f must be a function with one parameter (variable)')
  }
  
  h <- b - a
  
  fxdx <- (h / 2) * (f(a) + f(b))
  
  return(fxdx)
}


```



```{r function three}

f3 <- function(x) {
  return(exp(2 * x) * sin(3 * x))
}


## VISUALIZATION OF COMPOSITE TRAPEZOID ESTIMATION

# Break the interval into n subintervals
seg <- seq.int(0, 2, length.out = 9)

# Initialize an empty vector to store function outputs
fx <- vector(length = length(seg))

# For each subinterval, calculate the function
for (i in 1:length(seg)) {
  fx[i] <- f3(seg[i])
}

# Collect the needed points into a data.frame
df <- data.frame(xend = seg, 
                 y = rep(0, 9), 
                 yend = fx, 
                 yend1 = c(fx[2:9], fx[9]), 
                 xend1 = c(seg[2:9], seg[9]))

# plot the function and its approximation
ggplot(data = df) + 
  stat_function(fun = f3, size = 1.05, alpha = 0.75, color='blue') + 
  geom_segment(aes(x=xend, y=y, xend=xend, yend=yend)) + 
  geom_segment(aes(x=xend, y=yend, xend=xend1, yend=yend1)) + 
  geom_ribbon(aes(x=xend, ymin=y, ymax=yend), fill = 'blue', alpha = 0.3) + 
  geom_area(stat = 'function', fun = f3, fill = 'black', alpha = 0.3, xlim = c(0, 2)) + 
  xlim(c(-0.5, 2))



```



```{r comp trap}

#inputs: f = function, a = lower limit, b = upper limit, n = number of divisions
# from above:
#f <- function(x) {
#  return(x * sin(x))
#}

#As a refresher: the formula for the area of a trapezoid:
# A = 1/2h(b1 + b2). Or A = ((a+b)/2)h
# In our formula, the 1/2 * h becomes a constant that is distributed to the other terms (h / 2)

composite.trapezoid <- function(f, a, b, n) {
  if (is.function(f) == FALSE) {
    stop('f must be a function with one parameter (variable)') #I think this is a way to output an error message
  }
  
  h <- (b - a) / n #h = height of a single trapezoid on it's side.
  
  j <- 1:n - 1  #j = integer sequence from 1:n-1

  xj <- a + j * h #xj = variable given by: lower limit plus (lower limit + # of traps - 1) times h

  approx <- (h / 2) * (f(a) + (2 * sum(f(xj)) + f(b) ) )#    height divided by 2 (constant) * ( (y value at a))  +PLUS+
  # 2 times the (sum of y values at xj) +PLUS+  y values at b)
  
  return(approx)
}

composite.trapezoid(f3, 0, 2, 8)


```
```{r interpolation example}

x <- 1:10
y <- rnorm(10)
f <- approxfun(x, y)
curve(f(x), 0, 11, col = "green2")
points(x, y)
is.function(fc <- approxfun(x, y, method = "const")) # TRUE
curve(fc(x), 0, 10, col = "darkblue", add = TRUE)
## different extrapolation on left and right side :
plot(approxfun(x, y, rule = 2:1), 0, 11,
     col = "tomato", add = TRUE, lty = 3, lwd = 2)


```

## Code ideas: 
Modified from this Star Strider post on 21 Nov 2019:
Original code is for use in MATlab

[remove negative area](https://www.mathworks.com/matlabcentral/answers/492268-area-between-curve-numerical-data-with-positive-and-negative-values-and-y-0)

The general idea:
Separate out the values greater than 0. Calculate the areas separately. An additional note is to use interpolation to gain more precision with polygons defined by consecutive values with different signs. (crosses x-axis).

```{r}

x = c(0:100)
y = rnorm(101)
gt0 <- y[y>0]
print(gt0)

posArea = trapz(x(gt0), y(gt0));                       # % Area > 0
negArea = trapz(x(~gt0), y(~gt0));                     # % Area < 0

#I've already done the first part of separating the above-zero data and below-zero data using filter (See AUC_degree_day_trials.Rmd)

#Adding an interpolation part:

x <- order(1:100)
y <- sample(-22:40, 100, replace = TRUE)
length(x)
length(y)

df <- as.data.frame(cbind(x,y))



df$lead.y <- lead(df$y)
view(df)

FUN1 <- function(df){
  
  z.ct <- 0
  
  for(i in (1:nrow(df))){
    
    if(!is.na(df[i]$lead.y) & (df[i]$y * df[i]$lead.y < 0)){
  
  z.ct <- z.ct + 1
  print(z.ct)
}
}
}

sapply(seq_along(df), function(i){
  
  z.ct <- 0
    
    if(!is.na(df[[i]]$lead.y) & (df[[i]]$y * df[[i]]$lead.y < 0)){
  
  z.ct <- z.ct + 1
  print(z.ct)
}
  }
)

  
FUN1(df)

#FUN1(df)
lapply(df, FUN1)

pwalk(df, FUN1)

args(lapply)
#interp.FUN <- approx(x,y, xout = c(___))




```

